---
upload_path: "/forestryio/images"
frontmatter_file_url_template: "/forestryio/images"
body_file_url_template: "{{ site.baseurl }}/forestryio/images"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
